name: Check code with linter

on: push

jobs:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2  
  - name: Python Linter
    uses: sunnysid3up/python-linter@master
    with:
      source: "."
      strict: "high"
